// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaperCraft.Data;

#nullable disable

namespace PaperCraft.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250525100049_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PaperCraft.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PaperCraft.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Ручки",
                            Description = "Гладкое письмо, чёрные чернила",
                            ImageUrl = "/images/pen1.jpg",
                            Name = "Гелевая ручка",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Тетради",
                            Description = "Клетка, обложка с рисунком",
                            ImageUrl = "/images/notebook1.jpg",
                            Name = "Тетрадь 96 л.",
                            Price = 89.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Маркер",
                            Description = "Набор из 6 неоновых цветов",
                            ImageUrl = "/images/markers.jpg",
                            Name = "Маркеры для выделения",
                            Price = 149.50m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Карандаши",
                            Description = "С ластиком, 0.5 мм",
                            ImageUrl = "/images/mech-pencil.jpg",
                            Name = "Карандаш механический",
                            Price = 69.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Блокноты",
                            Description = "На спирали, 120 стр.",
                            ImageUrl = "/images/notepad.jpg",
                            Name = "Блокнот A5",
                            Price = 129.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Офис",
                            Description = "Металлические, 100 шт.",
                            ImageUrl = "/images/paperclips.jpg",
                            Name = "Скрепки",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Папки",
                            Description = "Формат A4, синяя",
                            ImageUrl = "/images/folder.jpg",
                            Name = "Папка-регистратор",
                            Price = 199.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Офис",
                            Description = "12-разрядный дисплей",
                            ImageUrl = "/images/calculator.jpg",
                            Name = "Калькулятор",
                            Price = 499.00m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Творчество",
                            Description = "Набор 24 цвета",
                            ImageUrl = "/images/color-pencils.jpg",
                            Name = "Цветные карандаши",
                            Price = 189.90m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Канцтовары",
                            Description = "Не оставляет следов",
                            ImageUrl = "/images/eraser.jpg",
                            Name = "Ластик",
                            Price = 29.00m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Клей",
                            Description = "15 г",
                            ImageUrl = "/images/glue-stick.jpg",
                            Name = "Клей-карандаш",
                            Price = 49.00m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Офис",
                            Description = "Удобные ручки, 21 см",
                            ImageUrl = "/images/scissors.jpg",
                            Name = "Ножницы офисные",
                            Price = 119.00m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Офис",
                            Description = "Набор разноцветных",
                            ImageUrl = "/images/sticky-tabs.jpg",
                            Name = "Стикеры-закладки",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Творчество",
                            Description = "12 цветов, водные",
                            ImageUrl = "/images/markers2.jpg",
                            Name = "Фломастеры",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Ручки",
                            Description = "Простая и надёжная",
                            ImageUrl = "/images/pen2.jpg",
                            Name = "Ручка с синей пастой",
                            Price = 19.00m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Офис",
                            Description = "Пластиковая, прозрачная",
                            ImageUrl = "/images/ruler.jpg",
                            Name = "Линейка 30 см",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Обложки",
                            Description = "Комплект 10 шт., А5",
                            ImageUrl = "/images/covers.jpg",
                            Name = "Обложки для тетрадей",
                            Price = 59.00m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Аксессуары",
                            Description = "На молнии, текстиль",
                            ImageUrl = "/images/pencil-case.jpg",
                            Name = "Пенал",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Офис",
                            Description = "Металлический, до 10 листов",
                            ImageUrl = "/images/hole-punch.jpg",
                            Name = "Дырокол",
                            Price = 179.00m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Офис",
                            Description = "Прозрачный, 18 мм",
                            ImageUrl = "/images/tape.jpg",
                            Name = "Скотч канцелярский",
                            Price = 33.00m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PaperCraft.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PaperCraft.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaperCraft.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PaperCraft.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
